version:  "3.8"

services:
  login-database:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER:  root
        POSTGRES_PASSWORD: my_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout:  5s
      retries: 10



