server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled:  true

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/
    

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info